### ISSUE TITLE
ERORR UNTUK REPLIT

### ISSUE THREAD

**Issue by Bintangp02** [Kangsad01/bot-md#1]
[Replit eror tak bisa untuk run, comand yang di copy tak berhasil untuk menyelesaikan masalah ffmpeg erorr, totolng di perbaiki lagi](https://github.com/Bintangp02)

note run replit erorr makasih.

**Comment by Kangsad01** [comment]
Okh nanti gw benerin

**Comment by Kangsad01** [comment]
![Screenshot_2022-05-26-12-43-39-45_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/88497118/170424497-d21a6ee0-b2bb-4b82-96a9-08bb3eec71ff.jpg)


Ni bisa

**Comment by ahmadqsyaa** [comment]
![Screenshot_20221003-205038](https://user-images.githubusercontent.com/114840842/193594639-8e6b0bb7-eeef-4eae-8b62-f4e355ebc7b4.png)
Bagaimana solusinya?

**Comment by Kangsad01** [comment]
> ![Screenshot_20221003-205038](https://user-images.githubusercontent.com/114840842/193594639-8e6b0bb7-eeef-4eae-8b62-f4e355ebc7b4.png) Bagaimana solusinya?

I don't know
