### ISSUE TITLE
Qr

### ISSUE THREAD

**Issue by Teamolduser** [Kangsad01/bot-md#27]
Where the qr i start using npm start but i cant qr

**Comment by Kangsad01** [comment]
> Where the qr i start using npm start but i cant qr

make sure to install the module

**Comment by Teamolduser** [comment]
I have installed all modules and in your Bailey not installing so i install adiwajshing Baileys and renamed to Baileys

**Comment by Kangsad01** [comment]
I suggest using this
https://www.mediafire.com/file/71ti9x10pulov85/node_modules.tar.gz/file

> I have installed all modules and in your Bailey not installing so i install adiwajshing Baileys and renamed to Baileys

**Comment by Teamolduser** [comment]
> I suggest using this https://www.mediafire.com/file/71ti9x10pulov85/node_modules.tar.gz/file
> 
> > I have installed all modules and in your Bailey not installing so i install adiwajshing Baileys and renamed to Baileys

If i can't get qr so what i want to do

**Comment by Teamolduser** [comment]
> I suggest using this https://www.mediafire.com/file/71ti9x10pulov85/node_modules.tar.gz/file
> 
> > I have installed all modules and in your Bailey not installing so i install adiwajshing Baileys and renamed to Baileys

Can you push it in GitHub?

**Comment by Kangsad01** [comment]
> > I suggest using this https://www.mediafire.com/file/71ti9x10pulov85/node_modules.tar.gz/file
> > > I have installed all modules and in your Bailey not installing so i install adiwajshing Baileys and renamed to Baileys
> 
> Can you push it in GitHub?

sorry can't

**Comment by Teamolduser** [comment]
> > > I suggest using this https://www.mediafire.com/file/71ti9x10pulov85/node_modules.tar.gz/file
> > > > I have installed all modules and in your Bailey not installing so i install adiwajshing Baileys and renamed to Baileys
> > 
> > 
> > Can you push it in GitHub?
> 
> sorry can't

Why

**Comment by teamolduser** [comment]
What to do next 


[](https://user-images.githubusercontent.com/120130487/214499229-eb000a98-81be-4831-962a-d71d3e9c64f5.jpg)

**Comment by Teamolduser** [comment]
WHAT TO DO NEXT


![@teamolduser ](https://user-images.githubusercontent.com/120130487/214499502-b7b89725-6f2e-49c7-b7ec-e3679cbb161d.jpg)

**Comment by Kangsad01** [comment]
> > > > I suggest using this https://www.mediafire.com/file/71ti9x10pulov85/node_modules.tar.gz/file
> > > > > I have installed all modules and in your Bailey not installing so i install adiwajshing Baileys and renamed to Baileys
> > > 
> > > 
> > > Can you push it in GitHub?
> > 
> > 
> > sorry can't
> 
> Why

because my cellphone was hit by an Android bug which experienced not being able to install apk outside of the Playstore

**Comment by Kangsad01** [comment]
> WHAT TO DO NEXT
> 
> ![@teamolduser ](https://user-images.githubusercontent.com/120130487/214499502-b7b89725-6f2e-49c7-b7ec-e3679cbb161d.jpg)

please wait for the improvement, because I want to focus on studying

**Comment by Teamolduser** [comment]
> > > > > I suggest using this https://www.mediafire.com/file/71ti9x10pulov85/node_modules.tar.gz/file
> > > > > > I have installed all modules and in your Bailey not installing so i install adiwajshing Baileys and renamed to Baileys
> > > > 
> > > > 
> > > > Can you push it in GitHub?
> > > 
> > > 
> > > sorry can't
> > 
> > 
> > Why
> 
> because my cellphone was hit by an Android bug which experienced not being able to install apk outside of the Playstore

What is link of installation of apk and uploading in GitHub

**Comment by Kangsad01** [comment]
> > > > > > Saya sarankan menggunakan ini https://www.mediafire.com/file/71ti9x10pulov85/node_modules.tar.gz/file
> > > > > > > Saya telah menginstal semua modul dan Bailey Anda tidak menginstal jadi saya menginstal adiwajshing Baileys dan berganti nama menjadi Baileys
> > > > > 
> > > > > 
> > > > > Bisakah Anda mendorongnya di GitHub?
> > > > 
> > > > 
> > > > maaf tidak bisa
> > > 
> > > 
> > > Mengapa
> > 
> > 
> > karena hp saya terkena bug android yang mengalami tidak bisa install apk diluar playstore
> 
> Apa itu tautan pemasangan apk dan mengunggah di GitHub

no, but my cellphone can't install third-party applications

**Comment by Teamolduser** [comment]
> Saya sarankan menggunakan ini https://www.mediafire.com/file/71ti9x10pulov85/node_modules.tar.gz/file
> Saya telah menginstal semua modul dan Bailey Anda tidak menginstal jadi saya menginstal adiwajshing Baileys dan berganti nama menjadi Baileys
>
>
> Bisakah Anda mendorongnya di GitHub?
>
>
> maaf tidak bisa
>
>
> Mengapa
> 
> 
>  karena hp saya terkena bug android yang mengalami tidak bisa install apk diluar playstore
> 
> 
>  Apa itu tautan pemasangan apk dan mengunggah di GitHub
> 
> no, but my cellphone can't install third-party applications

can you speak english else ingrish
