### ISSUE TITLE
Still in problem 😭😭😭😭😭😭

### ISSUE THREAD

**Issue by Teamolduser** [Kangsad01/bot-md#28]
Check the problem from  [Here 😭😭😭😭😭](https://github.com/sadteams/bot-md/issues/27#issuecomment-1403173438)

**Comment by Kangsad01** [comment]
> Check the problem from [Here 😭😭😭😭😭](https://github.com/sadteams/bot-md/issues/27#issuecomment-1403173438)

please wait for the improvement, because I want to focus on studying

**Comment by Teamolduser** [comment]
> > Check the problem from [Here 😭😭😭😭😭](https://github.com/sadteams/bot-md/issues/27#issuecomment-1403173438)
> 
> please wait for the improvement, because I want to focus on studying

Do you have any other bot like bot-md
